import type {
  Banner,
  Category,
  Order,
  Product,
  ReviewItem,
  Seller,
  WalletTxn,
} from "./types";

export const categories: Category[] = [
  {
    slug: "ai",
    name: "Tài khoản AI",
    short: "AI Accounts",
    iconKey: "sparkles",
    description: "ChatGPT, Claude, Gemini, Midjourney, Cursor, Perplexity...",
    color: "from-violet-500 to-fuchsia-500",
    productCount: 248,
  },
  {
    slug: "tool",
    name: "Tool / Phần mềm",
    short: "Software Tools",
    iconKey: "wrench",
    description: "Auto SEO, dropship, anti-detect, key Adobe / Microsoft...",
    color: "from-cyan-500 to-blue-500",
    productCount: 412,
  },
  {
    slug: "course",
    name: "Khoá học",
    short: "Courses",
    iconKey: "graduation-cap",
    description: "MMO, Affiliate, TikTok Shop, lập trình, marketing...",
    color: "from-emerald-500 to-teal-500",
    productCount: 186,
  },
  {
    slug: "giftcard",
    name: "Gift Card & Thẻ nạp",
    short: "Gift Cards",
    iconKey: "gift",
    description: "Steam, Netflix, Spotify, Garena, voucher Shopee/Lazada...",
    color: "from-pink-500 to-rose-500",
    productCount: 134,
  },
  {
    slug: "game",
    name: "Tài khoản & Skin Game",
    short: "Game Accounts",
    iconKey: "gamepad",
    description: "Liên Quân, LMHT, Valorant, PUBG, Genshin, Free Fire...",
    color: "from-amber-500 to-orange-500",
    productCount: 327,
  },
  {
    slug: "social",
    name: "Tài khoản MXH",
    short: "Social Accounts",
    iconKey: "users",
    description: "Facebook, TikTok, Instagram via/clone, BM, ad accounts...",
    color: "from-sky-500 to-indigo-500",
    productCount: 521,
  },
  {
    slug: "engagement",
    name: "Tăng tương tác",
    short: "Engagement",
    iconKey: "trending-up",
    description: "Like, follow, view, comment social, SEO traffic...",
    color: "from-lime-500 to-green-500",
    productCount: 92,
  },
  {
    slug: "bestseller",
    name: "Sản phẩm bán chạy",
    short: "Best Sellers",
    iconKey: "flame",
    description: "Top sản phẩm hot trên sàn 7 ngày qua",
    color: "from-red-500 to-orange-500",
    productCount: 50,
  },
];

export const sellers: Seller[] = [
  {
    id: "s1",
    username: "kimchi",
    displayName: "Kimchi Store",
    avatarColor: "#7c3aed",
    rating: 4.92,
    reviewCount: 2843,
    joinedAt: "2023-02-12",
    totalSold: 18450,
    badge: "top",
    responseTime: "< 5 phút",
    kycStatus: "approved",
    bio: "Chuyên cung cấp tài khoản AI cao cấp, bảo hành full thời gian sử dụng.",
  },
  {
    id: "s2",
    username: "quynhnhu",
    displayName: "Quỳnh Như Digital",
    avatarColor: "#22d3ee",
    rating: 4.86,
    reviewCount: 1402,
    joinedAt: "2023-08-20",
    totalSold: 9800,
    badge: "verified",
    responseTime: "< 15 phút",
    kycStatus: "approved",
    bio: "Tool MMO, phần mềm bản quyền, license key Adobe / Office.",
  },
  {
    id: "s3",
    username: "vyhan",
    displayName: "VyHan Premium",
    avatarColor: "#22c55e",
    rating: 4.78,
    reviewCount: 980,
    joinedAt: "2024-01-05",
    totalSold: 5300,
    badge: "verified",
    responseTime: "< 30 phút",
    kycStatus: "approved",
  },
  {
    id: "s4",
    username: "phatshop",
    displayName: "Phát Shop Game",
    avatarColor: "#f59e0b",
    rating: 4.71,
    reviewCount: 612,
    joinedAt: "2024-03-15",
    totalSold: 3200,
    badge: "verified",
    responseTime: "< 1 giờ",
    kycStatus: "approved",
  },
  {
    id: "s5",
    username: "duydeal",
    displayName: "DuyDeal Affiliate",
    avatarColor: "#ef4444",
    rating: 4.65,
    reviewCount: 410,
    joinedAt: "2024-06-01",
    totalSold: 1800,
    badge: "new",
    responseTime: "< 2 giờ",
    kycStatus: "approved",
  },
  {
    id: "s6",
    username: "namcenter",
    displayName: "Nam Center",
    avatarColor: "#0ea5e9",
    rating: 4.55,
    reviewCount: 285,
    joinedAt: "2024-09-10",
    totalSold: 940,
    badge: "verified",
    responseTime: "< 1 giờ",
    kycStatus: "approved",
  },
  {
    id: "s7",
    username: "ngochan",
    displayName: "NgocHan AI Hub",
    avatarColor: "#a855f7",
    rating: 4.83,
    reviewCount: 1120,
    joinedAt: "2023-11-03",
    totalSold: 7600,
    badge: "top",
    responseTime: "< 10 phút",
    kycStatus: "approved",
  },
  {
    id: "s8",
    username: "myshop",
    displayName: "MyShop Trading",
    avatarColor: "#14b8a6",
    rating: 4.42,
    reviewCount: 220,
    joinedAt: "2025-01-15",
    totalSold: 480,
    badge: "new",
    responseTime: "< 3 giờ",
    kycStatus: "pending",
  },
];

const longLorem =
  "Sản phẩm chính hãng, kích hoạt tự động ngay sau khi thanh toán. Bảo hành 1 đổi 1 trong suốt thời gian sử dụng nếu lỗi từ nhà cung cấp. Hỗ trợ kỹ thuật 24/7 qua chat trực tiếp trên sàn. Cam kết kiểm tra trùng sản phẩm trước khi giao hàng để đảm bảo bạn nhận được tài khoản chưa từng được bán cho ai khác.";

function makeProduct(p: Partial<Product> & Pick<Product, "id" | "title" | "category" | "price" | "sellerId">): Product {
  return {
    slug: p.slug ?? p.id,
    thumbnailColor: p.thumbnailColor ?? "#7c3aed",
    rating: p.rating ?? 4.6 + Math.random() * 0.4,
    reviewCount: p.reviewCount ?? Math.floor(50 + Math.random() * 800),
    sold: p.sold ?? Math.floor(20 + Math.random() * 500),
    stock: p.stock ?? Math.floor(20 + Math.random() * 200),
    delivery: p.delivery ?? "auto",
    warrantyDays: p.warrantyDays ?? 30,
    badges: p.badges,
    comparePrice: p.comparePrice,
    shortDescription:
      p.shortDescription ?? "Tài khoản chính hãng, giao tự động, bảo hành tận nơi.",
    description: p.description ?? longLorem,
    features: p.features ?? [
      "Kích hoạt tự động trong vòng 5 giây",
      "Bảo hành 1 đổi 1 nếu lỗi nhà cung cấp",
      "Hỗ trợ 24/7 qua live chat",
      "Hoàn tiền 100% nếu sai mô tả",
    ],
    policies: p.policies ?? [
      "Không chia sẻ cho bên thứ 3",
      "Đổi mật khẩu trong vòng 24h sau khi nhận",
      "Khiếu nại trong 72h kể từ khi nhận hàng",
    ],
    faq: p.faq ?? [
      { q: "Sản phẩm có dùng được trên nhiều thiết bị?", a: "Có, hỗ trợ tối đa 2-3 thiết bị tuỳ gói." },
      { q: "Nếu tài khoản bị die thì sao?", a: "Liên hệ shop, được đổi mới ngay trong thời gian bảo hành." },
      { q: "Thanh toán có an toàn không?", a: "Tiền được giữ trong escrow 3-7 ngày, chỉ giải phóng cho seller khi bạn xác nhận." },
    ],
    createdAt: p.createdAt ?? new Date(Date.now() - Math.random() * 1000 * 60 * 60 * 24 * 60).toISOString(),
    ...p,
  } as Product;
}

export const products: Product[] = [
  makeProduct({
    id: "p1",
    title: "ChatGPT Plus 1 Tháng — Chính Hãng, Nhận Liền",
    category: "ai",
    price: 199000,
    comparePrice: 499000,
    sellerId: "s1",
    badges: ["flash", "top"],
    thumbnailColor: "#10a37f",
    thumbnailIcon: "✨",
    warrantyDays: 30,
    rating: 4.92,
    reviewCount: 2143,
    sold: 8540,
    delivery: "auto",
    shortDescription: "Tài khoản ChatGPT Plus chính chủ, dùng riêng, đầy đủ GPT-4o, GPT-4.5, o1, DALL-E.",
  }),
  makeProduct({
    id: "p2",
    title: "Cursor AI Pro — IDE AI Code Siêu Nhanh, Max Mode",
    category: "ai",
    price: 220000,
    comparePrice: 599000,
    sellerId: "s6",
    badges: ["new", "top"],
    thumbnailColor: "#0ea5e9",
    thumbnailIcon: "⌘",
    rating: 4.78,
    reviewCount: 412,
    sold: 1230,
    warrantyDays: 30,
  }),
  makeProduct({
    id: "p3",
    title: "Claude Pro 1 Tháng — Anthropic Chính Hãng",
    category: "ai",
    price: 280000,
    comparePrice: 560000,
    sellerId: "s7",
    badges: ["top"],
    thumbnailColor: "#cc785c",
    thumbnailIcon: "C",
    rating: 4.85,
    reviewCount: 980,
    sold: 3210,
    warrantyDays: 30,
  }),
  makeProduct({
    id: "p4",
    title: "Gemini Advanced 2.5 — Bao Gồm Veo 3 Sinh Video",
    category: "ai",
    price: 320000,
    comparePrice: 690000,
    sellerId: "s7",
    badges: ["new"],
    thumbnailColor: "#1a73e8",
    thumbnailIcon: "G",
    rating: 4.71,
    reviewCount: 320,
    sold: 1100,
    warrantyDays: 30,
  }),
  makeProduct({
    id: "p5",
    title: "Midjourney v7 — Standard Plan",
    category: "ai",
    price: 350000,
    comparePrice: 720000,
    sellerId: "s1",
    thumbnailColor: "#a78bfa",
    thumbnailIcon: "🎨",
    rating: 4.66,
    reviewCount: 540,
    sold: 1800,
    warrantyDays: 30,
  }),
  makeProduct({
    id: "p6",
    title: "Capcut Pro 1 Năm — Bảo Hành Full Time",
    category: "tool",
    price: 89000,
    comparePrice: 250000,
    sellerId: "s2",
    badges: ["flash"],
    thumbnailColor: "#000000",
    thumbnailIcon: "▶",
    rating: 4.56,
    reviewCount: 980,
    sold: 4500,
    warrantyDays: 365,
  }),
  makeProduct({
    id: "p7",
    title: "Adobe Creative Cloud All Apps — Bản Quyền Quốc Tế",
    category: "tool",
    price: 990000,
    comparePrice: 1990000,
    sellerId: "s2",
    badges: ["top"],
    thumbnailColor: "#ed1c24",
    thumbnailIcon: "Ai",
    rating: 4.81,
    reviewCount: 412,
    sold: 980,
    warrantyDays: 365,
  }),
  makeProduct({
    id: "p8",
    title: "Tool Auto Like / Follow TikTok — Bản Pro",
    category: "tool",
    price: 450000,
    comparePrice: 990000,
    sellerId: "s3",
    thumbnailColor: "#fe2c55",
    thumbnailIcon: "♪",
    rating: 4.62,
    reviewCount: 230,
    sold: 540,
    warrantyDays: 90,
  }),
  makeProduct({
    id: "p9",
    title: "GoLogin / AdsPower — Anti-detect Browser, 50 Profile",
    category: "tool",
    price: 690000,
    comparePrice: 1290000,
    sellerId: "s2",
    thumbnailColor: "#0ea5e9",
    thumbnailIcon: "🛡",
    rating: 4.74,
    reviewCount: 180,
    sold: 320,
    warrantyDays: 30,
  }),
  makeProduct({
    id: "p10",
    title: "Khoá Học MMO Affiliate Toàn Tập 2025 — 60 Buổi",
    category: "course",
    price: 1200000,
    comparePrice: 4990000,
    sellerId: "s5",
    badges: ["top"],
    thumbnailColor: "#f59e0b",
    thumbnailIcon: "🎓",
    rating: 4.88,
    reviewCount: 320,
    sold: 1450,
    warrantyDays: 0,
    delivery: "auto",
  }),
  makeProduct({
    id: "p11",
    title: "Khoá Học TikTok Shop Bùng Nổ Doanh Thu",
    category: "course",
    price: 890000,
    comparePrice: 2490000,
    sellerId: "s5",
    thumbnailColor: "#fe2c55",
    thumbnailIcon: "📚",
    rating: 4.72,
    reviewCount: 180,
    sold: 720,
    warrantyDays: 0,
  }),
  makeProduct({
    id: "p12",
    title: "Combo Khoá Học Python + AI Engineering 2025",
    category: "course",
    price: 1490000,
    comparePrice: 3990000,
    sellerId: "s6",
    thumbnailColor: "#3776ab",
    thumbnailIcon: "🐍",
    rating: 4.83,
    reviewCount: 120,
    sold: 410,
    warrantyDays: 0,
  }),
  makeProduct({
    id: "p13",
    title: "Steam Wallet $50 — Mã Code Quốc Tế",
    category: "giftcard",
    price: 1290000,
    sellerId: "s4",
    thumbnailColor: "#1b2838",
    thumbnailIcon: "🎮",
    rating: 4.95,
    reviewCount: 1820,
    sold: 4200,
    warrantyDays: 0,
    delivery: "auto",
  }),
  makeProduct({
    id: "p14",
    title: "Netflix Premium 4K 1 Tháng — Dùng Riêng",
    category: "giftcard",
    price: 79000,
    comparePrice: 260000,
    sellerId: "s4",
    badges: ["flash"],
    thumbnailColor: "#e50914",
    thumbnailIcon: "N",
    rating: 4.58,
    reviewCount: 2340,
    sold: 9800,
    warrantyDays: 30,
  }),
  makeProduct({
    id: "p15",
    title: "Spotify Premium Family 1 Năm",
    category: "giftcard",
    price: 590000,
    comparePrice: 1290000,
    sellerId: "s4",
    thumbnailColor: "#1db954",
    thumbnailIcon: "♬",
    rating: 4.64,
    reviewCount: 1100,
    sold: 3200,
    warrantyDays: 365,
  }),
  makeProduct({
    id: "p16",
    title: "Voucher Shopee 500K — Áp Dụng Toàn Sàn",
    category: "giftcard",
    price: 420000,
    sellerId: "s8",
    thumbnailColor: "#ee4d2d",
    thumbnailIcon: "🛍",
    rating: 4.4,
    reviewCount: 320,
    sold: 1240,
    warrantyDays: 0,
  }),
  makeProduct({
    id: "p17",
    title: "Acc Liên Quân Vip — 70 Tướng, Full Skin SS",
    category: "game",
    price: 2490000,
    comparePrice: 4990000,
    sellerId: "s4",
    thumbnailColor: "#fbbf24",
    thumbnailIcon: "⚔",
    rating: 4.7,
    reviewCount: 84,
    sold: 36,
    warrantyDays: 7,
    delivery: "manual",
    badges: ["limited"],
  }),
  makeProduct({
    id: "p18",
    title: "Genshin Impact AR58 — Toàn DPS 5*",
    category: "game",
    price: 4900000,
    comparePrice: 8900000,
    sellerId: "s4",
    thumbnailColor: "#fde047",
    thumbnailIcon: "✦",
    rating: 4.5,
    reviewCount: 28,
    sold: 18,
    warrantyDays: 7,
    delivery: "manual",
  }),
  makeProduct({
    id: "p19",
    title: "Acc Valorant — Skin Reaver, Phantom Hữu Hạn",
    category: "game",
    price: 1290000,
    comparePrice: 2490000,
    sellerId: "s4",
    thumbnailColor: "#fa4454",
    thumbnailIcon: "▽",
    rating: 4.6,
    reviewCount: 56,
    sold: 22,
    warrantyDays: 7,
    delivery: "manual",
  }),
  makeProduct({
    id: "p20",
    title: "Skin Free Fire Quỷ Dạ Xoa Vĩnh Viễn",
    category: "game",
    price: 390000,
    comparePrice: 690000,
    sellerId: "s4",
    thumbnailColor: "#f97316",
    thumbnailIcon: "🔥",
    rating: 4.55,
    reviewCount: 92,
    sold: 140,
    warrantyDays: 7,
  }),
  makeProduct({
    id: "p21",
    title: "Acc Facebook Cổ 2010+ — Email Khoẻ",
    category: "social",
    price: 280000,
    sellerId: "s3",
    thumbnailColor: "#1877f2",
    thumbnailIcon: "f",
    rating: 4.32,
    reviewCount: 220,
    sold: 480,
    warrantyDays: 0,
  }),
  makeProduct({
    id: "p22",
    title: "BM5 Facebook Verify NV — Tạo Limit 250$",
    category: "social",
    price: 690000,
    sellerId: "s3",
    badges: ["top"],
    thumbnailColor: "#1877f2",
    thumbnailIcon: "BM",
    rating: 4.45,
    reviewCount: 180,
    sold: 320,
    warrantyDays: 14,
  }),
  makeProduct({
    id: "p23",
    title: "TikTok Có Giỏ Hàng — Affiliate Sẵn Sàng",
    category: "social",
    price: 1290000,
    sellerId: "s5",
    badges: ["flash"],
    thumbnailColor: "#000000",
    thumbnailIcon: "T",
    rating: 4.6,
    reviewCount: 80,
    sold: 120,
    warrantyDays: 14,
  }),
  makeProduct({
    id: "p24",
    title: "Instagram 10K Followers Thật — Việt Nam",
    category: "social",
    price: 990000,
    sellerId: "s8",
    thumbnailColor: "#E4405F",
    thumbnailIcon: "ig",
    rating: 4.2,
    reviewCount: 60,
    sold: 90,
    warrantyDays: 30,
  }),
  makeProduct({
    id: "p25",
    title: "Tăng 1000 View TikTok — Giữ Vĩnh Viễn",
    category: "engagement",
    price: 39000,
    sellerId: "s8",
    thumbnailColor: "#22d3ee",
    thumbnailIcon: "▲",
    rating: 4.5,
    reviewCount: 410,
    sold: 1820,
    warrantyDays: 0,
    delivery: "auto",
  }),
  makeProduct({
    id: "p26",
    title: "Tăng 500 Like Fanpage Việt — An Toàn",
    category: "engagement",
    price: 49000,
    sellerId: "s8",
    thumbnailColor: "#0ea5e9",
    thumbnailIcon: "♥",
    rating: 4.45,
    reviewCount: 320,
    sold: 1100,
    warrantyDays: 0,
  }),
  makeProduct({
    id: "p27",
    title: "Combo SEO Backlink PBN DA60+ Trọn Gói",
    category: "engagement",
    price: 1900000,
    sellerId: "s8",
    thumbnailColor: "#7c3aed",
    thumbnailIcon: "🔗",
    rating: 4.6,
    reviewCount: 80,
    sold: 110,
    warrantyDays: 0,
  }),
  makeProduct({
    id: "p28",
    title: "Duolingo Super VIP 1 Năm — Học Ngoại Ngữ",
    category: "giftcard",
    price: 290000,
    comparePrice: 690000,
    sellerId: "s4",
    thumbnailColor: "#58cc02",
    thumbnailIcon: "🦉",
    rating: 4.75,
    reviewCount: 240,
    sold: 380,
    warrantyDays: 365,
  }),
  makeProduct({
    id: "p29",
    title: "TradingView Premium 1 Năm — Bao Gồm Indicator",
    category: "tool",
    price: 1290000,
    comparePrice: 3490000,
    sellerId: "s2",
    thumbnailColor: "#2962ff",
    thumbnailIcon: "📈",
    rating: 4.8,
    reviewCount: 140,
    sold: 290,
    warrantyDays: 365,
  }),
  makeProduct({
    id: "p30",
    title: "Notion AI Plus 1 Năm — Workspace Pro",
    category: "ai",
    price: 690000,
    comparePrice: 1490000,
    sellerId: "s7",
    thumbnailColor: "#000000",
    thumbnailIcon: "N",
    rating: 4.7,
    reviewCount: 110,
    sold: 240,
    warrantyDays: 365,
  }),
];

export const reviews: ReviewItem[] = [
  {
    id: "r1",
    productId: "p1",
    buyerName: "Tuấn Anh",
    rating: 5,
    comment: "Mua 5 lần rồi, shop giao trong 3 giây, đăng nhập vào dùng được luôn. Quá đỉnh!",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    reply: "Cảm ơn anh đã ủng hộ shop, mong anh tiếp tục đồng hành ạ.",
  },
  {
    id: "r2",
    productId: "p1",
    buyerName: "Minh Khôi",
    rating: 5,
    comment: "Bảo hành nhanh, 1 lần bị 2FA shop xử lý liền trong 10 phút.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: "r3",
    productId: "p1",
    buyerName: "Hà Linh",
    rating: 4,
    comment: "Giá hợp lý, tài khoản dùng riêng đúng cam kết. Trừ 1 sao vì email reset hơi chậm.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
];

export const orders: Order[] = [
  {
    id: "MMK-1042855",
    buyerName: "Tôi",
    status: "COMPLETED",
    paymentMethod: "wallet",
    total: 199000,
    fee: 0,
    discount: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    lines: [
      {
        productId: "p1",
        title: "ChatGPT Plus 1 Tháng",
        unitPrice: 199000,
        quantity: 1,
        sellerId: "s1",
        delivery: "auto",
        deliveredItems: [
          { account: "user_42a8@protonmail.com", password: "********", note: "Vui lòng đổi mật khẩu trong 24h." },
        ],
      },
    ],
  },
  {
    id: "MMK-1042913",
    buyerName: "Tôi",
    status: "DELIVERED",
    paymentMethod: "vietqr",
    total: 1290000,
    fee: 0,
    discount: 50000,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
    lines: [
      {
        productId: "p13",
        title: "Steam Wallet $50",
        unitPrice: 1290000,
        quantity: 1,
        sellerId: "s4",
        delivery: "auto",
        deliveredItems: [
          { account: "Mã code: STM-50USD-AAA-XXXX-YYYY", note: "Áp dụng tại store.steampowered.com/account/redeemwalletcode" },
        ],
      },
    ],
  },
  {
    id: "MMK-1042966",
    buyerName: "Tôi",
    status: "PROCESSING",
    paymentMethod: "wallet",
    total: 2490000,
    fee: 0,
    discount: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    lines: [
      {
        productId: "p17",
        title: "Acc Liên Quân Vip 70 Tướng",
        unitPrice: 2490000,
        quantity: 1,
        sellerId: "s4",
        delivery: "manual",
      },
    ],
  },
  {
    id: "MMK-1043001",
    buyerName: "Tôi",
    status: "DISPUTE",
    paymentMethod: "vnpay",
    total: 690000,
    fee: 0,
    discount: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
    lines: [
      {
        productId: "p22",
        title: "BM5 Facebook Verify NV",
        unitPrice: 690000,
        quantity: 1,
        sellerId: "s3",
        delivery: "manual",
      },
    ],
  },
  {
    id: "MMK-1043120",
    buyerName: "Tôi",
    status: "PENDING_PAYMENT",
    paymentMethod: "vietqr",
    total: 89000,
    fee: 0,
    discount: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    lines: [
      {
        productId: "p6",
        title: "Capcut Pro 1 Năm",
        unitPrice: 89000,
        quantity: 1,
        sellerId: "s2",
        delivery: "auto",
      },
    ],
  },
];

export const walletTxns: WalletTxn[] = [
  {
    id: "WX-1",
    type: "topup",
    amount: 2000000,
    status: "completed",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    note: "Nạp ví qua VietQR — Vietcombank",
  },
  {
    id: "WX-2",
    type: "purchase",
    amount: -199000,
    status: "completed",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    note: "Đơn MMK-1042855 — ChatGPT Plus",
  },
  {
    id: "WX-3",
    type: "bonus",
    amount: 50000,
    status: "completed",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    note: "Bonus nạp 2tr tặng 50k",
  },
  {
    id: "WX-4",
    type: "purchase",
    amount: -2490000,
    status: "pending",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    note: "Đơn MMK-1042966 — Liên Quân (đang giữ escrow)",
  },
  {
    id: "WX-5",
    type: "commission",
    amount: 25000,
    status: "completed",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    note: "Hoa hồng affiliate đơn của @minhk",
  },
];

export const banners: Banner[] = [
  {
    id: "b1",
    title: "Công Cụ AI Sức Mạnh",
    subtitle: "Combo ChatGPT + Claude + Gemini chỉ từ 20K/tháng",
    badge: "FLASH SALE",
    href: "/c/ai",
    gradient: "from-violet-600 via-fuchsia-600 to-pink-500",
  },
  {
    id: "b2",
    title: "App Học Tập 15K/Tháng",
    subtitle: "Duolingo, Quizlet, Notion AI Plus...",
    badge: "MỚI",
    href: "/c/giftcard",
    gradient: "from-cyan-500 via-sky-500 to-indigo-600",
  },
  {
    id: "b3",
    title: "Adobe & Microsoft Bản Quyền",
    subtitle: "Giá tốt nhất thị trường — Bảo hành full thời gian",
    badge: "TOP",
    href: "/c/tool",
    gradient: "from-rose-500 via-orange-500 to-amber-500",
  },
  {
    id: "b4",
    title: "Hệ Sinh Thái Google",
    subtitle: "Gemini Advanced + Veo 3 + 2TB Drive",
    badge: "DUY NHẤT",
    href: "/c/ai",
    gradient: "from-emerald-500 via-teal-500 to-cyan-500",
  },
];

export const adminMetrics = {
  gmv: 2_482_550_000,
  revenue: 198_604_000, // 8% phí sàn
  newUsers: 1284,
  ordersCompleted: 12_842,
  kycPending: 23,
  productsPending: 41,
  openDisputes: 7,
  pendingWithdraw: 12,
  topupToday: 142_750_000,
};

export function getProduct(slug: string) {
  return products.find((p) => p.slug === slug || p.id === slug);
}

export function getSeller(id: string) {
  return sellers.find((s) => s.id === id);
}

export function getCategory(slug: string) {
  return categories.find((c) => c.slug === slug);
}

export function productsByCategory(slug: string) {
  return products.filter((p) => p.category === slug);
}

export function topProducts(n = 8) {
  return [...products].sort((a, b) => b.sold - a.sold).slice(0, n);
}

export function flashSaleProducts() {
  return products.filter((p) => p.badges?.includes("flash"));
}

export function newProducts(n = 8) {
  return [...products]
    .sort((a, b) => +new Date(b.createdAt) - +new Date(a.createdAt))
    .slice(0, n);
}
